[package]
name = "nun"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
